version: '2.2'
services:
    forms_app:
      build:
        context: .
      ports:
        - "5000:5000"
#      volumes:
#        - ./logs/forms_app:/forms_app/logs
      command: gunicorn forms_app.wsgi_app:app --bind 0.0.0.0:5000  --reload
      networks:
        - forms_network

    nginx:
      image: nginx:1.19.2
      volumes:
        - /tmp/logs/nginx/:/var/log/nginx/
        - ./deploy/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./deploy/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      depends_on:
        - users_actions_app
      ports:
        - 8080:80
      networks:
        - forms_network

    mongodb:
      image: mongo
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: your_username
        MONGO_INITDB_ROOT_PASSWORD: your_password

      networks:
        - forms_network


    mongo-express:
      image: mongo-express
      container_name: mongo-express
      restart: always
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      links:
        - mongodb
      networks:
        - forms_network


networks:
  forms_network:
    name: forms_network
    external: true


volumes:
  mongodb_data: