version: '2.2'
services:

    mongodb:
      image: mongo
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/data/db
      networks:
        - forms_network

    mongo-express:
      image: mongo-express
      container_name: mongo-express
      restart: always
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
        ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_LOGIN}
        ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      networks:
        - forms_network


networks:
  forms_network:
    name: forms_network
    external: true


volumes:
  mongodb_data: