version: '2.2'
services:

    mongodb:
      image: mongo
      container_name: mongodb
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/data/db
      networks:
        - forms_network
#      environment:
#        MONGO_INITDB_ROOT_USERNAME: annn
#        MONGO_INITDB_ROOT_PASSWORD: passs
#        MONGO_INITDB_DATABASE: form_db
#      command: ["--auth"]


    mongo-express:
      image: mongo-express
      container_name: mongo-express
      restart: always
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
        ME_CONFIG_BASICAUTH_USERNAME: ann
        ME_CONFIG_BASICAUTH_PASSWORD: pass
#
#        ME_CONFIG_MONGODB_ADMINUSERNAME: annn
#        ME_CONFIG_MONGODB_ADMINPASSWORD: passs

      networks:
        - forms_network


networks:
  forms_network:
    name: forms_network
    external: true


volumes:
  mongodb_data: